---
title: "First Knit"
author: "Roxan Barakat"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: yes
    toc_depth: '5'
  html_document:
    number_sections: yes
    toc: yes
    toc_depth: 5
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
I attended Lancaster High School and graduated in June of 2020. English and Math are two different subjects, Math is usually for left-brained individuals and English is for right-brained people. Math requires problem-solving and logic, on the other hand, English is for expression and creativity. In my opinion, Math is an easier subject than English, because it's a universal language that is taught worldwide. I did best in Math during my High school years due to my mother being an engineer and teaching me math at a young age. Math is a fun subject that is considered a brain workout. 

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  At home, I have a Mac book which is an Apple brand. When it comes to my computer experience, I rate myself a 5 out of 10 because I am not a complete ignorant yet I'm not an expert either. I do have an internet connection at home, it's fairly good, yet not the best at certain times.
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  I prefer to be called by my first name "Roxan." If I have a choice to have a nickname, it would be "Roxy", but I don't mind being called by my first name by everyone, in fact, I like it!
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   
 






  




